language: node_js

node_js:
  - '10.15.3'

script:
  - node --version
  - npm install
  - npm run sass-lint
  - npm run lint
  - npm run deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ASIYANA_DEPLOYMENT
  local-dir: build
  keep-history: true
  on:
    branch: master

git:
  depth: 10
