language: node_js

node_js:
  - "8"

script:
  - node --version
  - npm install
  - npm run deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: build
  keep-history: true
  on:
    branch: master

git:
  depth: 10
